project:
  type: website
  output-dir: docs

website:
  title: "Kavana Raju - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4"
          - href: weekly-notes/week-05-notes.qmd
            text: "Week 5"
          - href: weekly-notes/week-06-notes.qmd
            text: "Week 6"
          - href: weekly-notes/week-07-notes.qmd
            text: "Week 7"
          - href: weekly-notes/week-09-notes.qmd
            text: "Week 9"
          - href: weekly-notes/week-10-notes.qmd
            text: "Week 10"

      - text: "Assignments"
        menu:
          - href: assignments/assignment_1/assignment1_template.qmd
            text: "Assignment 1: Census Data Exploration" 
          - href: assignments/assignment_2/assignment2/assignment2.qmd
            text: "Assignment 2:Spatial Analysis and Visualization" 
          - href: assignments/assignment_3/model_script.qmd
            text: "Assignment 3: Technical Appendix"
          - href: assignments/assignment_3/midterm_presentation.qmd
            text: "Assignment 3: Presentation"
          - href: assignments/assignment_4/assignment_4/assignment_4.qmd
            text: "Assignment 4: Spatial Predictive Analysis"
          - href: assignments/assignment_5/assignment_5.qmd
            text: "Assignment 5: Space-Time Prediction of Bike Share Demand"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
